# mandatory
blog_name: "Docsie.io Blog"
blog_root_url: "blog"
blog_post_location_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vR2Unb1VTOB1upja915Rp7N6MJnqtLLOPYUlrJW7R0qybH_kGWB1wPozgjAf6X5JD-Bv_XldO9yKSLU/pub?output=csv"
domain_url: "https://www.docsie.io"

# optional
link_menu:
  - link: "https://www.docsie.io"
    text: "Docsie"
  - link: "https://www.docsie.io/pricing/"
    text: "Docsie Pricing"
  - link: "https://www.docsie.io/try_docsie/"
    text: "Try Docsie"

search_config:
  title:
    weight: 8
  summary:
    weight: 6
  author_name:
    weight: 5
  categories:
    weight: 3

comments:
  enabled: true
  commentbox_project_id: "5725910686760960-proj"

subscribe:
  enabled: true
  title: "Subscribe to the newsletter"
  summary: "Stay up to date with our latest news and products"
  button_text: "Subscribe"

sharect:
  enabled: true
  twitter: true
  facebook: true
  twitterUsername: ""
  backgroundColor: "#333333"
  iconColor: "#FFFFFF"
  selectableElements:
    - body

landing_meta:
  title: "Documentation Insights | Docsie - Articles on Better Docs, Marketing, Technology & More"
  description: "Documentation Insights is where our team shares documentation tips, stories and lessons learned about creating better documentation experiences."
  image: "https://www.docsie.io/assets/share-image.jpeg"
  keywords: "Documentation, docs, product documentation, user manual, software documentation"
  url: "https://www.docsie.io/blog/"
  author: "Docsie.io"

google_tag_manager:
  enabled: true
  google_tag_manager_projectid: "GTM-TZRGMQ9"